### ISSUE TITLE
stuck at finalizing

### ISSUE THREAD

**Issue by soyabkhanmalek** [D3VL/L3MON#1]
web page stuck at finalizing status after building apk but apk file is build successfully and after installing apk no devices showing on webpage. sorry for bad english.

**Comment by Jack-Rogers** [comment]
Please check the event logs page for any errors and also make sure java is installed.

If java is installed, please run 
`java -version` 
And send the output.

Also, what OS are you using?

**Comment by soyabkhanmalek** [comment]
there is no error on logs page and the java version is-
java version "1.8.0_221"
Java(TM) SE Runtime Environment (build 1.8.0_221-b11)

**Comment by soyabkhanmalek** [comment]
ok ,so i builded the apk from android studio and installed in android device and checked with packet  capture.Sending data to exect ip address i assigned but not listed(showing) on LEMON device list in online or offline.

**Comment by Jack-Rogers** [comment]
Have you checked that port 22222 is allowed through your host's firewall?

**Comment by ch4iril** [comment]
try on linux
update-alternatives --config java
select number 2 :
open-8-jdk

if you use 
open-11-jdk not work to build apk

**Comment by harishsg99** [comment]
For  me also same problem  i used aws ubuntu instance.......its show build successful but when installed app on phone its not showing device in lemon webpage
I followed and done as you said in readme
Please help me to fix
Upto which android version it supports please help me

**Comment by ziadmhadddad** [comment]
plz how can know  in http://<SERVER IP>:22533  what is the server ip??

**Comment by miladzero** [comment]
> Please check the event logs page for any errors and also make sure java is installed.
> 
> If java is installed, please run
> `java -version`
> And send the output.
> 
> Also, what OS are you using?

root@kali:~# java -version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk version "11.0.6-ea" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6-ea+7-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.6-ea+7-post-Debian-1, mixed mode, sharing)

**Comment by Jack-Rogers** [comment]
@miladzero  Please make sure to use Java 1.8.0, not 11.0.6!

**Comment by Jack-Rogers** [comment]
This has now been fixed in version 1.1.0! 
Download it here https://github.com/D3VL/L3MON/releases/
