### ISSUE TITLE
Hey @jack-rogers do a remote-session..

### ISSUE THREAD

**Issue by yatharthmaheshwari** [D3VL/L3MON#102]
Hope You are Healthy and Safe,

Hat's off to the amount of effort You have been putting on L3MON even during these Hard times

I think it is very necessary that you have a remote-control session with me which allows you to experience the problem more deeply. And may the solution to the Problem Arrive.

You may have some extra time during this pandemic so kindly inform me on my Gmail
<-- yatharthmaheshwari2004@gmail.com -->

#stay safe, wash hands

regards 
Yatharth Maheshwari.

**Comment by Jack-Rogers** [comment]
Definitely not got any extra time at the moment, We're all very busy here at D3VL!

I'll send you an email to discuss this.
Cheers
