### ISSUE TITLE
no voice in microphone

### ISSUE THREAD

**Issue by MisterChangRay** [D3VL/L3MON#103]
**This is an issue with the**
- [x] Server
- [x] Client
- [ ] Other

**Describe the bug**
microphone not work in android 9,  is need root?

**Comment by Jack-Rogers** [comment]
This shouldn't need root, there's been ALOT of issue with android 9.0 recently, unfortunately I don't have a 9.0 so I'm relying on community error file submissions to solve this. 
Please can you upload a ADB logcat of the app crashing when you run the voice command?

**Comment by MisterChangRay** [comment]
This is the log when capturing audio
[microphone.txt](https://github.com/D3VL/L3MON/files/4587599/microphone.txt)


 but the app not crash;

**Comment by MisterChangRay** [comment]
view document and some permission need dynamic apply

i check log find this:

05-06 22:58:33.342   937   937 E MediaRecorderService: Request requires android.permission.RECORD_AUDIO
05-06 22:58:33.343 11474 11525 W System.err: java.lang.RuntimeException: setAudioSource failed.
05-06 22:58:33.344 11474 11525 W System.err: 	at android.media.MediaRecorder.setAudioSource(Native Method)
05-06 22:58:33.344 11474 11525 W System.err: 	at com.etechd.l3mon.MicManager.startRecording(MicManager.java:42)
05-06 22:58:33.344 11474 11525 W System.err: 	at com.etechd.l3mon.ConnectionManager.MI(ConnectionManager.java:150)
05-06 22:58:33.345 11474 11525 W System.err: 	at com.etechd.l3mon.ConnectionManager$2.call(ConnectionManager.java:78)
05-06 22:58:33.345 11474 11525 W System.err: 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
05-06 22:58:33.345 11474 11525 W System.err: 	at io.socket.client.Socket.onevent(Socket.java:340)
05-06 22:58:33.345 11474 11525 W System.err: 	at io.socket.client.Socket.onpacket(Socket.java:293)
05-06 22:58:33.345 11474 11525 W System.err: 	at io.socket.client.Socket.access$100(Socket.java:19)
05-06 22:58:33.345 11474 11525 W System.err: 	at io.socket.client.Socket$2$2.call(Socket.java:111)
05-06 22:58:33.345 11474 11525 W System.err: 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
05-06 22:58:33.346 11474 11525 W System.err: 	at io.socket.client.Manager.ondecoded(Manager.java:407)
05-06 22:58:33.346 11474 11525 W System.err: 	at io.socket.client.Manager.access$1600(Manager.java:20)
05-06 22:58:33.346 11474 11525 W System.err: 	at io.socket.client.Manager$7.call(Manager.java:383)
05-06 22:58:33.346 11474 11525 W System.err: 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
05-06 22:58:33.346 11474 11525 W System.err: 	at io.socket.parser.Parser$Decoder.add(Parser.java:157)
05-06 22:58:33.346 11474 11525 W System.err: 	at io.socket.client.Manager.ondata(Manager.java:399)
05-06 22:58:33.346 11474 11525 W System.err: 	at io.socket.client.Manager.access$1000(Manager.java:20)
05-06 22:58:33.347 11474 11525 W System.err: 	at io.socket.client.Manager$2.call(Manager.java:350)
05-06 22:58:33.347 11474 11525 W System.err: 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
05-06 22:58:33.347 11474 11525 W System.err: 	at io.socket.engineio.client.Socket.onPacket(Socket.java:511)
05-06 22:58:33.347 11474 11525 W System.err: 	at io.socket.engineio.client.Socket.access$1000(Socket.java:31)
05-06 22:58:33.347 11474 11525 W System.err: 	at io.socket.engineio.client.Socket$5.call(Socket.java:313)
05-06 22:58:33.347 11474 11525 W System.err: 	at io.socket.emitter.Emitter.emit(Emitter.java:117)
05-06 22:58:33.347 11474 11525 W System.err: 	at io.socket.engineio.client.Transport.onPacket(Transport.java:134)
05-06 22:58:33.348 11474 11525 W System.err: 	at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17)
05-06 22:58:33.348 11474 11525 W System.err: 	at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124)
05-06 22:58:33.348 11474 11525 W System.err: 	at io.socket.engineio.parser.Parser.decodePayload(Parser.java:188)
05-06 22:58:33.348 11474 11525 W System.err: 	at io.socket.engineio.client.transports.Polling._onData(Polling.java:132)
05-06 22:58:33.348 11474 11525 W System.err: 	at io.socket.engineio.client.transports.Polling.onData(Polling.java:101)
05-06 22:58:33.348 11474 11525 W System.err: 	at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:109)
05-06 22:58:33.348 11474 11525 W System.err: 	at io.socket.thread.EventThread$2.run(EventThread.java:80)
05-06 22:58:33.349 11474 11525 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
05-06 22:58:33.349 11474 11525 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
05-06 22:58:33.349 11474 11525 W System.err: 	at java.lang.Thread.run(Thread.java:764)
05-06 22:58:33.352  3226 10918 D MediaScannerService: done scanning file: /storage/emulated/0/tencent/MicroMsg/Download/4_application.properties
05-06 22:58:33.352 10893 11016 I FileExplorer: MediaScanUtil scan file completed.

**Comment by Jack-Rogers** [comment]
In your error log file
`Permission failure: android.permission.RECORD_AUDIO`

You must give the application all permissions on installation or features (like this) will not work!
You can check the currently allowed permission by going to the permissions tab in the device manager.
