### ISSUE TITLE
Bad Login

### ISSUE THREAD

**Issue by yasithar** [D3VL/L3MON#104]
hello sir,
i was changed maindb.jason file user name as lowercase plain text and password as md5 hash generated code, you said but cant log into l3mon 
it says bad login

**Comment by yatharthmaheshwari** [comment]
try it several time may it work..

**Comment by Jack-Rogers** [comment]
Ensure you ran 'pm2 stop all' before editing and 'pm2 restart all' after saving.

**Comment by yasithar** [comment]
Yes i ran  "sudo stop pm2 all" before edit the maindb.json file then save
it and ran "sudo pm2 restart all" comand but still hapen the bad login
interface

So i tried many many times beginning to the end of procedure.. i dont know
where i the my fault.
Thank you!

**Comment by Jack-Rogers** [comment]
Try this website for generating the MD5 hash https://www.md5hashgenerator.com/
This hash is for 'password' and is confirmed to work **eff7d5dba32b4da32d9a67a519434d3f**

If neither of those work, delete all the files and try again.

**Comment by infected521** [comment]
hello very good night master, I hope you are well, I have the same bad login problem, and when generating the md5 key I have no problem, I do not know if it has something to do with the operating system, before using Ubuntu 14 and 16 and right now I use 18 gives me this error, regards

**Comment by yatharthmaheshwari** [comment]
Hey @infected521 ,
As far I think is you are missing some steps.
if you want to I can try to help you through a remote-session on the team-viewer.

Till then, just follow some tutorials on Youtube, One might work.

MyGmail: yatharthmaheshwari2004@gmail.com

**Comment by infected521** [comment]
Hola @rushyamaheshwari

You can finally solve it was that I had a problem in my vps, I installed it with the script that I sent you, it installs everything at first and it is self-installable, greetings and thanks for your attention

**Comment by yatharthmaheshwari** [comment]
@infected521 Congrutalations Brother

**Comment by Jack-Rogers** [comment]
Closing as solved / contained issue
