### ISSUE TITLE
How to run the server in public..?!

### ISSUE THREAD

**Issue by jmaxojan** [D3VL/L3MON#106]
Can you guys help me how to expose is it to the public, because when I open ports in the router the ip will change and I will lose them as it is in ngrok, I have edited `ngrok.yml` and linked http to tcp and it worked fine but when I build an apk it says there is an error and I can't receive the listener session, I used heruko as well but when I upload the server it ban my account automatically, any more ideas please help me as soon as you can.

**Comment by Jack-Rogers** [comment]
Try using an OVH VPS for hosting this. Heroku is not suitable as it doesn't retain storage of edited files once the instance restarts. 

Removing the bug label too as this is not a bug.

**Comment by Jack-Rogers** [comment]
closing as stale
