### ISSUE TITLE
5/15/2020, 11:44:25 PM => ERROR | Build Failed - Unable to spawn Java - Error: spawn java ENOENT

### ISSUE THREAD

**Issue by hasssanezzz** [D3VL/L3MON#107]
**This is an issue with the**
- [ ] Server
- [x] Client
- [ ] Other

**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Server Issue (please complete the following information):**
 - OS: [e.g. Linux, Windows]
 - OS Version: [e.g. Ubuntu, Windows 10]
 - Browser: [e.g. chrome, safari]

**Client Issue:**
 - Android Version: [e.g. Android 8]

**Checklist**
 - [x] Is this really an issue?
 - [x] Have I looked at previous issues to see if this has already been addressed?
 - [ ] Have I used some initiative to try and solve the issue myself?

**Comment by hasssanezzz** [comment]
When I am building the apk file it gives me this error

**Comment by Jack-Rogers** [comment]
Closing as you haven't even attempted to fill in the provided template.
