### ISSUE TITLE
Device Offline

### ISSUE THREAD

**Issue by s1st3r** [D3VL/L3MON#108]
Why are devices saying offline even when online and i have enabled all permissions on target device?

**Comment by Jack-Rogers** [comment]
Probably something todo with battery management on the device, at a guess? I'm not really able to assist without any logs or supporting information.

**Comment by s1st3r** [comment]
Actually no, both my phones are on, pm2 has been restarted, tested on a public solo VPS server. JDK is good, and both phones are up. Both phones-tables _Huawei_ (Throw Away tablets after moving to apple devices.)

**Comment by Jack-Rogers** [comment]
That doesn't mean to say the service hasn't been stopped in the background.
Search through the closed issues for Huawei, iirc I've addressed this before.

**Comment by Jack-Rogers** [comment]
My bad it was Xaomi see #4 it might be relevant

**Comment by s1st3r** [comment]
I have bought an older Techno and i will test that issue number #4 and see if i get somewhere.
