### ISSUE TITLE
java error

### ISSUE THREAD

**Issue by r4jesh** [D3VL/L3MON#111]
23/05/2020, 16:12:35 => ERROR | Build Failed - Wrong Java Version Installed. Detected openjdk version "11.0.7" 20. Please use Java 1.8.0

**Comment by Jack-Rogers** [comment]
I can't even begin to fathom what the issue could be here. 
Have you tried reading the error?

**Comment by glennbracey13** [comment]
lol

**Comment by r4jesh** [comment]
how to fix this

**Comment by Jack-Rogers** [comment]
Try reading the error and take a wild guess? 
Hint: use java 1.8.0

**Comment by glennbracey13** [comment]
READ
