### ISSUE TITLE
Error: Unable to access jarfile apktool

### ISSUE THREAD

**Issue by teknosmanli** [D3VL/L3MON#114]
Error: Unable to access jarfile apktool
what is this i am use windows not working

**Comment by Jack-Rogers** [comment]
Please check that apktool.jar is still in the folder `/app/factory` if it is - try running L3MON as Administrator and if not, or that doesn't work - try redownloading L3MON

**Comment by Jack-Rogers** [comment]
closing as stale - contained issue
