### ISSUE TITLE
bad login error

### ISSUE THREAD

**Issue by Zein-4** [D3VL/L3MON#116]
So basically I started the server and navigated to the login then it sad bad login, I know that the password has to be lowercase md5 so i will show you my maindb file.
{
  "admin": {
    "username": "admin",
    "password": " 8c7e845bbfd7e7e0266975099e6d4801",
    "loginToken": "",
    "logs": [],
    "ipLog": []
  },
  "clients": []
}

Also does this work on WSL or should i use it on VM?

**Comment by Zein-4** [comment]
Nv, i got it

**Comment by fgabcy** [comment]
delete the space between " and 8
