### ISSUE TITLE
Device offline

### ISSUE THREAD

**Issue by saravanakumarsk** [D3VL/L3MON#117]
The victims device online 
But the software shows victim was offline 
Then how to reconnect to the victim? The is the major problem in this software

**Comment by Jack-Rogers** [comment]
please refrain from using the word "victim" - this infers you're using the software for malicious purposes and thus we will not be able to support you. 
We use the terms "client" and "server". Thanks.

**Comment by saravanakumarsk** [comment]
Bro sry bro

Plzzzzzz give the solution for me bro

The device goes to offline automatically 🥺
