### ISSUE TITLE
ERROR | Build Failed - Wrong Java Version Installed.

### ISSUE THREAD

**Issue by kali-linux-tutorial** [D3VL/L3MON#118]
I am using Kali Linux 2020.1 and followed every steps carefully. But got this error when try to building APK.
`ERROR | Build Failed - Wrong Java Version Installed. Detected openjdk version "11.0.5" 20. Please use Java 1.8.0`
I have installed JAVA Runtime using following command:
`sudo apt-get install openjdk-8-jre`
**Now what to do?
![Screenshot_2020-06-13_20-42-56](https://user-images.githubusercontent.com/62602243/84572619-ec674500-adb8-11ea-846b-ff0012465248.png)
**

**Comment by MTA3** [comment]
Any solution?

**Comment by jaykali** [comment]
Here in my [this article](https://www.kalilinux.in/2020/06/l3mon-access-android-remotely-kali-linux.html) I showed how I solved this error.

**Comment by MTA3** [comment]
Thanks you, it worked for me

**Comment by MTA3** [comment]
@jaykali I did everything, but at the moment of infecting a device and opening the application. This does not appear in the system
