### ISSUE TITLE
Wrong Java Version Installed.

### ISSUE THREAD

**Issue by MutebAsiri** [D3VL/L3MON#120]
Im using Linux 

L3mon-v1.1.2
=> ERROR | Build Failed - Wrong Java Version Installed. Detected openjdk version "11.0.6" 20. Please use Java 1.8.0

and im stuck at finalizing

**Comment by MutebAsiri** [comment]
sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
to use java 1.8.0 . srry i didnt pay attention quite well

**Comment by yogeshjoga** [comment]
Wrong Java Version Installed. Detected OpenJDK version "11.0.11
![Screenshot (452)](https://user-images.githubusercontent.com/36118169/123988024-48f9ca00-d9e5-11eb-9ae0-982e043aa38e.png)
" 20. Please use Java 1.8.0
  please help me any one please
