### ISSUE TITLE
Can't  manage anything

### ISSUE THREAD

**Issue by slowzy5** [D3VL/L3MON#124]
Hello guys
i created an a rat with this tool and it works i mean devices show in the victime tabs but when i click on manage , everything then is empty ,no phone calls no file manager i don't know why it keeps happenning i downloaded the rat on my phone which has no antivirus and my phone is full of files but nothing shows when i click on manage 
please help
sorry for my bad english

**Comment by Jack-Rogers** [comment]
please refrain from using the word "victim" - this infers you're using the software for malicious purposes and thus we will not be able to support you.
We use the terms "client" and "server". Thanks.
