### ISSUE TITLE
system cannot execute the specified program

### ISSUE THREAD

**Issue by Kartikkaushal4546** [D3VL/L3MON#127]
Hello, when I go to change the username and password this will show "The system cannot execute the specified program" please tell me what to do now.
![error pnh](https://user-images.githubusercontent.com/68266035/87388568-b63d0100-c5c2-11ea-83f3-e8c792bbb384.PNG)

**Comment by fgabcy** [comment]
> Hello, when I go to change the username and password this will show "The system cannot execute the specified program" please tell me what to do now.
> ![error pnh](https://user-images.githubusercontent.com/68266035/87388568-b63d0100-c5c2-11ea-83f3-e8c792bbb384.PNG)

use (**nano maindb.json**) command

**Comment by yatharthmaheshwari** [comment]
Hey kartik, 
The maindb.json file is located in l3mon folder. You can open the file just like you would open a notepad file.

**Comment by yatharthmaheshwari** [comment]
I would recommend you to use Linux.

**Comment by Jack-Rogers** [comment]
closing as @yatharthmaheshwari answer to "use notepad" is the answer to the issue here.
