### ISSUE TITLE
app is not sending data from phone to server

### ISSUE THREAD

**Issue by Mudasir121725** [D3VL/L3MON#131]
**This is an issue with the**
- [x] Server
- [ ] Client
- [x] Other

**Describe the bug**
i have downloaded the app and install in the phone Samsung galaxy s6 but the force stop button in app is gray its not sending data to server. please help to solve the issue thank you

**Comment by Jack-Rogers** [comment]
Try checking if there's some battery management/antivirus running that could be stopping the process.
I'm closing this issue though as not enough information has been provided.

**Comment by Mudasir121725** [comment]
Why closing the issue if not resolved it's not working even I give it priority on battery usage in background

**Comment by Jack-Rogers** [comment]
There's no logs, you haven't used the provided issue template and you haven't described what you've tried to fix this problem. We're not miracle workers and we can only help diagnose an issue when we have all the information avaliable.
That is why i've closed this issue, because, 
>not enough information has been provided
