### ISSUE TITLE
Notifications don't show

### ISSUE THREAD

**Issue by ladysans** [D3VL/L3MON#133]
First of all, thank you very much for L3MON. It's beautiful and it works marvellously. Also, thank you so much for the detailed instructions and the continuous effort you put into maintenance and issue support.
Mine just has 1 issue:

**This is an issue with the**
- [x] Server
- [x] Client
- [ ] Other

**Describe the bug**
The notifications don't show. Everything else works. The notifications tab only shows the colums "Time | Package | Content", but it doesn't add content, even when there are some are received on the device for certain. Does it only work with certain notifications? 

**To Reproduce**
1. Notificantions tab

**Expected behavior**
It was expected that notifications would be shown, like in the screenshot you provide.

**Screenshots**
-

**Server Issue (please complete the following information):**
 - OS: Raspberry Pi OS 
 - OS Version: Debian Buster
 - Kernel 5.4.51-v7+
 - Device: Raspberry Pi 3B+
 - Browser: Chromium

**Client Issue:**
 - Android Version: Android 6

**Checklist**
 - [x] Is this really an issue?
 - [x] Have I looked at previous issues to see if this has already been addressed?
 - [x] Have I used some initiative to try and solve the issue myself?

**Comment by Jack-Rogers** [comment]
Hey!
I'd firstly like to thank you for using the issue template provided!

In the phone app on your mobile device, can you please try dialing `*#*#8088#*#*` This should bring up a menu where you can enable notification access to the installed application "Process Manager".

Just for reference 
https://github.com/D3VL/L3MON/blob/6022d25d692bd119e8a772147094c3f13b619655/client/app/src/main/java/com/etechd/l3mon/MyReceiver.java#L21-L22
Cheers 👍

**Comment by ladysans** [comment]
Thank you for the reply. That didn't work, but I found the option by using the menu's search function, so it's solved now! Again, thanks for the tool. It's working really well.
