### ISSUE TITLE
Getting Error while building APK using apkbuilder

### ISSUE THREAD

**Issue by MahedialiBhatt** [D3VL/L3MON#137]
**This is an issue with the**
- [x] Server
- [ ] Client
- [x] Other

**Describe the bug**
getting some error while apk building
![Screenshot (21)](https://user-images.githubusercontent.com/48710193/92298731-8f1f0200-ef69-11ea-9c4a-cc1206cec203.png)
.

**To Reproduce**
1. Go to 'xyz.ngrok.io/apkbuilder'
2. Click on 'set ip and port then click on build'
3. See error

**Expected behavior**
I am not getting apk finalizing stuck and getting error.

**Screenshots**
![error](https://user-images.githubusercontent.com/48710193/92298659-f2f4fb00-ef68-11ea-92b3-d3961ed4f826.PNG)

JAVA VERSION IS-
![error 2](https://user-images.githubusercontent.com/48710193/92298882-1de04e80-ef6b-11ea-8c42-560e2b96d90f.PNG)

**Server Issue (please complete the following information):**
 - OS: [Windows]
 - OS Version: [Windows 10]
 - Browser: [chrome]

**Client Issue:**
 - Android Version: [e.g. Android 8]

**Checklist**
 - [ ] Is this really an issue?
 - [ ] Have I looked at previous issues to see if this has already been addressed?
 - [ ] Have I used some initiative to try and solve the issue myself?

**Comment by Jack-Rogers** [comment]
Hmm, looking at the error it appears L3MON doesn't have the right file permissions to edit the files needed.
Could you please try one or more of the following;
- running L3MON from a different directory
- changing the containing file permissions, 
- running L3MON as admin - To run as admin on windows you can use the key press WIN+X, click on "powershell (as Admin)" OR "cmd (as Admin)", navigate to the directory and try running from there.
- If the above 3 solutions don't solve the issue, have a look at #76 that may be of help as it's a similar error, though not the same.

**Comment by MahedialiBhatt** [comment]
i download apktool and change lemon apktool with new one and its work fine

**Comment by MahedialiBhatt** [comment]
i wnat to know how to use public ip inl3min?

**Comment by Jack-Rogers** [comment]
Excellent stuff! Glad you got it resolved 😄 
To use an external IP, you need to either run L3MON on a VPS (as it's designed to be run) or open port `22222` on your router.

**Comment by MahedialiBhatt** [comment]
any free vps available??

**Comment by Jack-Rogers** [comment]
Nope, you have to pay for them. You can pick up a cheap one at OVH https://www.ovhcloud.com/en-gb/vps/

As this issue is now solved, i'm going to close it.
