### ISSUE TITLE
make payload persistence

### ISSUE THREAD

**Issue by MahedialiBhatt** [D3VL/L3MON#139]
I am using ngrok and it works perfectly . but when i restart my pc ngrok gives new forwarding address so old payload  becomes useless so what to do for payload persistence ?? or how to use public ip in ngrok ??

**Comment by Jack-Rogers** [comment]
This software is designed to be run on a VPS with a STATIC ip address, not from your home computer! 
Please try using a VPS and that should solve this issue.

**Comment by azamet90** [comment]
> This software is designed to be run on a VPS with a STATIC ip address, not from your home computer!
> Please try using a VPS and that should solve this issue.

i have only 1 ip address on my home network it not changes and i did open port im not loosing the target because of ip but im loosing it because of after reboot the app crashes ...
