### ISSUE TITLE
devices wont connect to server

### ISSUE THREAD

**Issue by m4rioc89** [D3VL/L3MON#144]
**This is an issue with the**
- [x] Server
- [ ] Client
- [ ] Other

**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**
have opened the 22533 port on my vps (both udp/tcp), everything works fine, i build the apk addressing my vpn dns with 22533 port but when Install the apk in my devices the list wont show my devices.  datasaver is off.

**Screenshots**

**Server Issue (please complete the following information):**
 - OS: [e.g. Linux, Windows]
 - OS Version: [e.g. Ubuntu, Windows 10]
 - Browser: [e.g. chrome, safari]

**Client Issue:**
 - Android Version: [e.g. Android 8]

**Checklist**
 - [ ] Is this really an issue?
 - [ yes, another user reported it] Have I looked at previous issues to see if this has already been addressed?
 - [ ] Have I used some initiative to try and solve the issue myself?

**Comment by vpnfreefree** [comment]
facing same issue

**Comment by junied12** [comment]
what to do

**Comment by Jack-Rogers** [comment]
You also need port `22222` open, this is used for control purposes, `22533` is for the web ui only.
