### ISSUE TITLE
Could not identify aapt binary as executable

### ISSUE THREAD

**Issue by emirbyte** [D3VL/L3MON#146]
apkmod -r "/data/data/com.termux/files/usr/share/lemon/server/app/factory/decompiled" -o "/data/data/com.termux/files/home/lemon/build.apk"
Could not identify aapt binary as executable.

Please help!

**Comment by Jack-Rogers** [comment]
Not quite sure where you've got this command from but it's not part of L3MON. 
Try this? https://bit.ly/2UXM6l3
