### ISSUE TITLE
22533/login?e=badLogin / bad login

### ISSUE THREAD

**Issue by MR-N0B0DY7** [D3VL/L3MON#148]
I opened my IP22533 but everytime want to enter to account show error bad login......
I use user admin and md5 for password 
Rechange maindb.json by visual studio code , Agian.
open 2 different browser and check a lot of time 
But every time got "BAD LOGIN" error

**Comment by MDROSHANN** [comment]
I think You tried to edit the maindb.json  by renaming it to maindb.txt and after editing you changed it maindb.json right
