### ISSUE TITLE
Restarting or turning on the device loses control

### ISSUE THREAD

**Issue by DarknessAr** [D3VL/L3MON#151]
**This is an issue with the**
- [ ] Server
- [X] Client
- [ ] Other

**Describe the bug**
If the device turns off when you turn it on again, the application does not appear to start so device control is lost even if the device is turned on

**To Reproduce**
1. Go to 'reboot device or shutdown'
2. Click on 'turn on again.'
3. See error 'device shows offline'

**Expected behavior**
The app should start automatically when you start the device

**Server Issue (please complete the following information):**
 - OS: [Linux]
 - OS Version: [Ubuntu]
 - Browser: [Chrome]

**Client Issue:**
 - Android Version: [Android 7.0] All permissions have been given to the application, including battery and network restriction.

**Checklist**
 - [X] Is this really an issue?
 - [X] Have I looked at previous issues to see if this has already been addressed?
 - [No one has addressed this issue] Have I used some initiative to try and solve the issue myself?

**Comment by vpnfreefree** [comment]
looks like no solution to such problems of vps,server, public ip not connecting  and als after restarting

**Comment by stochlin777** [comment]
This happens because the application needs to be reopened when the phone is shut off and turned back on. That doesn't mean it doesn't work. Metetpreter does this as well. every android backdoor does. Im just wondering how the main coder bypassed androids power saving application killer.

**Comment by Jack-Rogers** [comment]
@DarknessAr specifically, what device is this running on, please? (EG: Samsung Galaxy Note 7, Android 7.0) Cheers!
