### ISSUE TITLE
unable to see other devices, only last device which went offline is visible , i created l3mon app 2 to 3 times more and installed through vps ip and my own public ip

### ISSUE THREAD

**Issue by vpnfreefree** [D3VL/L3MON#152]
yet not getting this issue solved.
please let me know how to make apk and see where other devices are connected or not. ALSO HOW TO USE DUCK DNS, PORTMAP, VPS IP HERE AND CREATE AND GET THE DEVICE.

CREATED L3MON APK WITH VPS IP AND MY OWN IP ADDRESS RESPECTIVELY BUT NONE WORKED.
BASICALLY HOW TO DEAL WITH PORTMAP.IO OR DUCKDNS OR VPS SERVICE IN THIS L3MON RAT ALSO PLEASE GUIDE THE STEPS TO HANDLE MULTIPLE DEVICES.

PLEASE PLEASE DO HELP ME OUT.

**Comment by vpnfreefree** [comment]
@Jack-Rogers man what more information you want and why did you close the issue without providing a solution to this

**Comment by Jack-Rogers** [comment]
#150
