### ISSUE TITLE
Devices show always offline unless the app (on the phone) is open

### ISSUE THREAD

**Issue by jepgarcia24** [D3VL/L3MON#156]
**This is an issue with the**
- [x] Server
- [ ] Client
- [ ] Other

**Describe the bug**
The devices shows offline unless I have the app open on the phone. 

**To Reproduce**
1. Install apk on phone and give all permissions. Then close it.
2. On the website, check for online status
3. Devices always show offline.

**Client Issue:**
 - OnePlus 6 Android 10.

**Comment by Jack-Rogers** [comment]
Does the Device have any battery managment features on it? 
And if you set up a command to be queued, does it eventually execute?

**Comment by jepgarcia24** [comment]
The device has a battery saving feature (which is disabled).
And yes, if I open the app, the commands get executed.

**Comment by jepgarcia24** [comment]
Looks like I found the problem, there's a Optimization battery featured (by app) that I have to disabled and now I see the device always online. Thank you!

**Comment by Jack-Rogers** [comment]
Awesome stuff, Oh btw, Welcome to GitHub and thanks for using the provided template! 
I'll close this issue now, if there's anything else, please open up a new one 👌
