### ISSUE TITLE
Secure for personal use

### ISSUE THREAD

**Issue by BilawalSh** [D3VL/L3MON#162]
I am using L3mon but i think it share data with third party because it not allow to delete data? is it secure? and please verify any expert

**Comment by Jack-Rogers** [comment]
L3MON is completely stand alone, to delete data you can find it in the `clientData` folder. 
L3MON does not presently use SSL, though if desired this can be easily implemented by the end user. 

Just to reitterate, no device data is shared with any third parties, we do collect usage statistics via google analytics on the webpanel, again easy to remove if desired, you can find it here `/assets/views/partials/head.ejs`.
