### ISSUE TITLE
Deleting data

### ISSUE THREAD

**Issue by ChanKnox** [D3VL/L3MON#179]
**This is an issue with the**
- [x] Server

**Describe the bug**
I have deleted all the files in /clientData but all data still gets displayed when logging in to the server. Contacts, clipboard log, notifications log, etc - it's all there.

**Expected behavior**
As mentioned in https://github.com/D3VL/L3MON/issues/162 the client data is stored in /clientData. The purpose of this issue is to find a way to delete the data for reasons of privacy.

**Comment by Jack-Rogers** [comment]
1. stop the node process 
2. delete data in `/clientData`
3. start the node process
