### ISSUE TITLE
Getting error while trying to build apk

### ISSUE THREAD

**Issue by Nasyx-Rakeeb** [D3VL/L3MON#181]
Hello,
I have kali linix aarch64 installed on my machine. I recently installed l3mon in it. I also installed java 1.8.0 all is working perfect but at the end when it reaches **FINALIZING** it shows me this error:

`Build Command Failed - Command failed: java -jar "/home/kali/Desktop
/L3mon/app/factory/apktool.jar" b "/home/kali/Desktop/L3mon
/app/factory/decompiled" -o "/home/kali/Desktop/L3mon/assets
/webpublic/build.apk" S: WARNING: Could not write to (/home/kali/.local
/share/apktool/framework), using /tmp instead...S: Please be aware this
is a volatile directory and frameworks could go missing, please utilize
--frame-path if the default storage directory is unavailable
brut.androlib. AndrolibException: brut.common.BrutException: could not
exec (exit code = 132): (/tmp/brut util Jar 8037937602728660564.tmp
p. --forced-package-id, 127. --min-5dk-version, 11, --target-sdk-version,
24, --Version-code, 1. --version-name, 1.0, --no-version-vectors, -F,
/tmp/APKTOOL6285777498437144193.tmp. -0, arsc, -0. png. -0, arsc, -1,
/tmp/1.apk -5, /home/kali/Desktop/L3mon/app/factory/decompiled/res,
-M. /home/kali/Desktop/L3mon/app/factory/decompiled
JAndroid Manifest.xml]`
@Jack-Rogers

**Comment by Jack-Rogers** [comment]
Takes 2 seconds to use search. You're looking for #76
