### ISSUE TITLE
Java not installed

### ISSUE THREAD

**Issue by 7h3pr0xy** [D3VL/L3MON#19]
I have installed java as per the requirements, but still im getting the issue that java is not installed

**Comment by Jack-Rogers** [comment]
Could you please run `java -version` and send back the output.

**Comment by 7h3pr0xy** [comment]
root@kali:~# java -version
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

**Comment by falconistic** [comment]
---------------------------------------------------------------------------------------------------------------
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Debian-2)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Debian-2, mixed mode, sharing)
---------------------------------------------------------------------------------------------------------------

**Comment by falconistic** [comment]
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk 11.0.5 2019-10-15
OpenJDK Runtime Environment (build 11.0.5+10-post-Debian-2)
OpenJDK 64-Bit Server VM (build 11.0.5+10-post-Debian-2, mixed mode, sharing)

**Comment by Jack-Rogers** [comment]
Could you please edit the following line in 'apkBuilder.js'

https://github.com/etechd/L3MON/blob/acbc29be4db0bd2cf297dcbf61086fa6829c9e37/server/includes/apkBuilder.js#L9

Change the line to
```JavaScript
spawn.on('error', (err) => callback("Unable to spawn java - " + err, null));
```

and send back the error here, if it's still "Java Not Installed" please still let me know

**Comment by Jack-Rogers** [comment]
The above change has been applied to v1.1.0 just released, please download it here https://github.com/D3VL/L3MON/releases/

**Comment by KeepWannabe** [comment]
same problem here, i use latest version of L3MON but "Java Not Installed" still showing up.

**Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)**

run on Nginx Server + Kali OS

**Comment by Jack-Rogers** [comment]
Thanks, I think I've narrowed down the issue, I'll have a look thisevening and push an update 👍

**Comment by Jack-Rogers** [comment]
Could you please edit the following file replacing this code
https://github.com/D3VL/L3MON/blob/20897ae4d2deabc108eaf487857e7441cc809f1b/server/includes/apkBuilder.js#L10-L19

With this
```JavaScript
spawn.stderr.on('data', (data) => {
    data = data.toString();
    let javaIndex = data.indexOf('java version');
    let openJDKIndex = data.indexOf('openjdk version');
    let javaVersion = (javaIndex !== -1) ? data.substring(javaIndex, (javaIndex + 27)) : false;
    let openJDKVersion = (openJDKIndex !== -1) ? data.substring(openJDKIndex, (openJDKIndex + 27)) : false;
    if (javaVersion || openJDKVersion) {
        if (javaVersion.includes("1.8.0") || openJDKVersion.includes("1.8.0")) {
            spawn.removeAllListeners();
            spawn.stderr.removeAllListeners();
            return callback(null, (javaVersion || openJDKVersion));
        } else return callback("Wrong Java Version Installed. Detected " + (javaVersion || openJDKVersion) + ". Please use Java 1.8.0", undefined);
    } else return callback("Java Not Installed", undefined);
});
```
I believe the error is coming because your system is putting out `Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true` and the code is selecting the first line expecting it to be `openjdk version "1.8.0_212"`.
Once confirmed to work I'll push a new release, Thanks!

**Comment by Jack-Rogers** [comment]
@KeepWannabe Are you able to confirm if this patch worked?

**Comment by yashithlalwani** [comment]
> @KeepWannabe Are you able to confirm if this patch worked?

I've tried the patch on v1.1.0 and can confirm it doesn't work.

**Comment by ch4iril** [comment]
i was install L3mon on my android devices, everything all work


thanks Jack for updated version

**Comment by Jack-Rogers** [comment]
@yashithlalwani 
> I've tried the patch on v1.1.0 and can confirm it doesn't work.
could you please run `java -version` and send back the output?

**Comment by Jack-Rogers** [comment]
Ah, my mistake!  That code wouldn't work as it'd be running `.includes()` on `undefined`.

Give this a try, 
```JavaScript
spawn.stderr.on('data', (data) => {
    data = data.toString();
    let javaIndex = data.indexOf('java version');
    let openJDKIndex = data.indexOf('openjdk version');
    let javaVersion = (javaIndex !== -1) ? data.substring(javaIndex, (javaIndex + 27)) : "";
    let openJDKVersion = (openJDKIndex !== -1) ? data.substring(openJDKIndex, (openJDKIndex + 27)) : "";
    if (javaVersion !== "" || openJDKVersion !== "") {
        if (javaVersion.includes("1.8") || openJDKVersion.includes("1.8")) {
            spawn.removeAllListeners();
            spawn.stderr.removeAllListeners();
            return callback(null, (javaVersion || openJDKVersion));
        } else return callback("Wrong Java Version Installed. Detected " + (javaVersion || openJDKVersion) + ". Please use Java 1.8.0", undefined);
    } else return callback("Java Not Installed", undefined);
});
```

**Comment by hack69** [comment]
@jack 
i have pasted ur code in apkbuilder.js as per u said .... but still same error (java not installed)

**Comment by sleepingspy999** [comment]
@hack69
Although i get the same error and it seems to hang on finalizing the apk is actually built and works perfectly.

**Comment by hack69** [comment]
Ur talking about build.apk ??
In my case (build.apk) is not getting install!!! Can u guide me through
it??

**Comment by sleepingspy999** [comment]
In the event log it shows this..
05/02/2020, 04:42:10 => SUCCESS | Build Succeded!
05/02/2020, 04:42:06 => ERROR | Build Failed - Java Not Installed

The apk is build.s.apk 
Install on device chamge permissions to everything works like a charm have tried it on Marshmellow and Android 10

**Comment by ch4iril** [comment]
hack69
how many java version on your OS?
11, 12 and 8 java version?
yesterday i try install on my macbook, always failed with error command sign jar bla bla bla
i decide remove all java except java 8
so now like a charm to build apk ..
maybe that can solved
i hope

**Comment by Jack-Rogers** [comment]
@sleepingspy999 
> Although i get the same error and it seems to hang on finalizing the apk is actually built and works perfectly.

-- Could you please confirm you're running v1.1.0, this issue should have been fixed! 


@hack69 
>i have pasted ur code in apkbuilder.js as per u said .... but still same error (java not installed)

-- Could you please run `java -version` and send back the output for us?

**Comment by sleepingspy999** [comment]
Running Kali Linux and the last update updated some node.js stuff no longer have this problem.

**Comment by Try2swipe** [comment]
> Running Kali Linux and the last update updated some node.js stuff no longer have this problem.

Same problem here, tried everything above, nothing works, @sleepingspy999 can you tell us what you exactly did please? Thanks

**Comment by Jack-Rogers** [comment]
@Try2swipe  have you applied my latest patch? If so, you're most likely running 2 versions of Java or don't have Java 1.8 installed at all, please run `java -version` and send back the output.

**Comment by ratpunk2** [comment]
Java not installed error whenever trying to built the apk file. My Java version is 1.8
![Screenshot_2020-02-13_10-36-33](https://user-images.githubusercontent.com/56511721/74453323-43f7b180-4ea8-11ea-9b76-85c6ddd2551f.png)

**Comment by Try2swipe** [comment]
> @Try2swipe have you applied my latest patch? If so, you're most likely running 2 versions of Java or don't have Java 1.8 installed at all, please run `java -version` and send back the output.

I got Java 11 installed, deleted the directory already, now every time I run `update-alternatives --config java` this is the output shown to me:

`update-alternatives: warning: alternative /usr/lib/jvm/java-11-openjdk-amd64/bin/java (part of link group java) doesn't exist; removing from list of alternatives
There is 1 choice for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      auto mode
* 1            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: `

I don't know if there's anything else that I need to do to get rid of the other Java version (11) than deleting the directory where Java 8 is located too, I mean "/usr/lib/jvm/"

And this is the output you asked for when I run `java -version`:

`Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)`

Thanks for your help :)

**Comment by Try2swipe** [comment]
> > @Try2swipe have you applied my latest patch? If so, you're most likely running 2 versions of Java or don't have Java 1.8 installed at all, please run `java -version` and send back the output.
> 
> I got your latest patch and, I also got Java 11 installed, I deleted the directory already, now every time I run `update-alternatives --config java` this is the output shown to me:
> 
> update-alternatives: warning: alternative /usr/lib/jvm/java-11-openjdk-amd64/bin/java (part of link group java) doesn't exist; removing from list of alternatives
> There is 1 choice for the alternative java (providing /usr/bin/java).
> ## Selection Path Priority Status
> 
> 0 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java 1081 auto mode
> 
>     * 1            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode
> 
> 
> Press to keep the current choice[*], or type selection number: 
> 
> I don't know if there's anything else that I need to do to get rid of the other Java version (11) than deleting the directory where Java 8 is located too, I mean "/usr/lib/jvm/"
> 
> And this is the output you asked for when I run `java -version`:
> 
> `Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true openjdk version "1.8.0_212" OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01) OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)`
> 
> Thanks for your help :)

**Comment by Try2swipe** [comment]
> @Try2swipe have you applied my latest patch? If so, you're most likely running 2 versions of Java or don't have Java 1.8 installed at all, please run `java -version` and send back the output.

I got you latest patch installed already, and I also noticed I had Java 11 installed too, I deleted the directory already, now every time I run `update-alternatives --config java` this is the output shown to me:

update-alternatives: warning: alternative /usr/lib/jvm/java-11-openjdk-amd64/bin/java (part of link group java) doesn't exist; removing from list of alternatives
There is 1 choice for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      auto mode
* 1            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 

I don't know if there's anything else that I need to do to get rid of the other Java version (11) than deleting the directory where Java 8 is located too, I mean "/usr/lib/jvm/"

And this is the output you asked for when I run `java -version`:

`Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true openjdk version "1.8.0_212" OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01) OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)`

Thanks for your help :)

**Comment by Try2swipe** [comment]
> @Try2swipe have you applied my latest patch? If so, you're most likely running 2 versions of Java or don't have Java 1.8 installed at all, please run `java -version` and send back the output.

I got you latest patch installed already. I noticed I had Java 11 installed too, I deleted the directory and now every time I run `update-alternatives --config java` this is the output shown to me:

update-alternatives: warning: alternative /usr/lib/jvm/java-11-openjdk-amd64/bin/java (part of link group java) doesn't exist; removing from list of alternatives
There is 1 choice for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority   Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      auto mode
* 1            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode

Press <enter> to keep the current choice[*], or type selection number: 

I don't know if there's anything else that I need to do to get rid of the other Java version (11) than deleting the directory where Java 8 is located too, I mean "/usr/lib/jvm/"

This is the output you asked for when I run `java -version`:

`Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true openjdk version "1.8.0_212" OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01) OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)`

Thanks for your help :)

**Comment by Jack-Rogers** [comment]
Thanks @ratpunk2 for the screenshot, it probably goes without saying, however, have you restarted L3MON after using the patch? 
I'll have a deeper look into this shortly.

**Comment by ratpunk2** [comment]
> Thanks @ratpunk2 for the screenshot, it probably goes without saying, however, have you restarted L3MON after using the patch?
> I'll have a deeper look into this shortly.

Yes I restarted the L3MON several times but whenever trying to build the payload , getting "Java not installed" error. I even reinstalled the JavaJDK and tried JavaJRE as well.

**Comment by ratpunk2** [comment]
> Thanks @ratpunk2 for the screenshot, it probably goes without saying, however, have you restarted L3MON after using the patch?
> I'll have a deeper look into this shortly.

**Comment by ratpunk2** [comment]
> > Thanks @ratpunk2 for the screenshot, it probably goes without saying, however, have you restarted L3MON after using the patch?
> > I'll have a deeper look into this shortly.

Yes I restarted the L3MON several times but whenever trying to build the payload , getting "Java not installed" error. I even reinstalled the JavaJDK and tried JavaJRE as well.

**Comment by yatharthmaheshwari** [comment]
> I have installed java as per the requirements, but still im getting the issue that java is not installed

Bro did You got it fixed??????

**Comment by yatharthmaheshwari** [comment]
> > @Try2swipe have you applied my latest patch? If so, you're most likely running 2 versions of Java or don't have Java 1.8 installed at all, please run `java -version` and send back the output.
> 
> I got you latest patch installed already. I noticed I had Java 11 installed too, I deleted the directory and now every time I run `update-alternatives --config java` this is the output shown to me:
> 
> update-alternatives: warning: alternative /usr/lib/jvm/java-11-openjdk-amd64/bin/java (part of link group java) doesn't exist; removing from list of alternatives
> There is 1 choice for the alternative java (providing /usr/bin/java).
> 
> ## Selection Path Priority Status
> 0 /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java 1081 auto mode
> 
> * 1            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081      manual mode
> 
> Press to keep the current choice[*], or type selection number:
> 
> I don't know if there's anything else that I need to do to get rid of the other Java version (11) than deleting the directory where Java 8 is located too, I mean "/usr/lib/jvm/"
> 
> This is the output you asked for when I run `java -version`:
> 
> `Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true openjdk version "1.8.0_212" OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01) OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)`
> 
> Thanks for your help :)

You mean we have to delete the older java version

**Comment by yatharthmaheshwari** [comment]
@Jack-Rogers Can You share your Linux version..i have updated to the latest version this might be the 
  culprit here.
and if Your linux version is also the latest then latest version of kali will not be the issue.

and if your kali is older, i will install older kali versions on vm , and update You guys about the issue

**Comment by ratpunk2** [comment]
> 
> 
> @Jack-Rogers Can You share your Linux version..i have updated to the latest version this might be the
> culprit here.
> and if Your linux version is also the latest then latest version of kali will not be the issue.
> 
> and if your kali is older, i will install older kali versions on vm , and update You guys about the issue

I tried on both (Kali linux 2019.04 and 2020.01) and having the same error "Java not installed". Already switched to Java8 (the required one).

**Comment by H4A-HUB** [comment]
How to install "openjdk-8-jre" on android. Thank you ^.^

**Comment by yatharthmaheshwari** [comment]
go watch an youtube video by nitesh

**Comment by ch4iril** [comment]
@H4A-HUB 

How to install "openjdk-8-jre" on android. Thank you ^.^








your android must be root

first step install termux , search on play store


second step 
you must instal AnLinux , search APK on play store 

select Kali

watch tutorial on youtube how install kali on AnLinux

**Comment by ratpunk2** [comment]
> nitesh

Please provide the link.

**Comment by rehman555** [comment]
java not installed @Jack-Rogers

**Comment by kobocrew** [comment]
i have only the java8 installed on kali 2020.1. when i try to build the apk a pop up msg sais no java and the apk build stops at finalizing

**Comment by rnemani96** [comment]
@Jack-Rogers 
I have updated the patch that you mentioned running the latest VM and updated kali too
![java build fail lmon](https://user-images.githubusercontent.com/26691959/77000460-70f32480-697e-11ea-88e9-247866a5b9a9.PNG)
![java fail l3mon](https://user-images.githubusercontent.com/26691959/77000461-718bbb00-697e-11ea-96c9-6e353ad7e4da.PNG)


![java selection](https://user-images.githubusercontent.com/26691959/77000447-6df83400-697e-11ea-9267-54cb6b6fc4bf.PNG)

**Comment by yatharthmaheshwari** [comment]
Rajesh NImani  Ji Please try it with ubuntu

**Comment by rnemani96** [comment]
@yatharthmaheshwari how to make it work with kali instead of ubuntu

**Comment by Lorenz11x** [comment]
@Jack-Rogers
Hi Lord,
Tested on VM Kali Linux 2020 with NAT, it also works perfectly with Ngrok ..., but on a fixed operating system installed on Notebook it doesn't work, I tried to install it several times but it always repeats the Java popout not installed, Can it be solved?. Also, I could share these little tricks to improve:

    # Using Debian, as root
curl -sL https://deb.nodesource.com/setup_13.x | bash -
apt-get install -y nodejs

 sudo apt-get update && sudo apt-get install yarn







:~/Desktop#  npm install pm2 -g
/usr/bin/pm2 -> /usr/lib/node_modules/pm2/bin/pm2
/usr/bin/pm2-dev -> /usr/lib/node_modules/pm2/bin/pm2-dev
/usr/bin/pm2-docker -> /usr/lib/node_modules/pm2/bin/pm2-docker
/usr/bin/pm2-runtime -> /usr/lib/node_modules/pm2/bin/pm2-runtime
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@~2.1.2 (node_modules/pm2/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ pm2@4.2.3
updated 1 package in 17.499s


:~/Desktop# npm install -g npm
/usr/bin/npm -> /usr/lib/node_modules/npm/bin/npm-cli.js
/usr/bin/npx -> /usr/lib/node_modules/npm/bin/npx-cli.js
+ npm@6.14.3
updated 1 package in 14.093s


Thanks and sorry for my English !!

**Comment by ch4iril** [comment]
@kobocrew


have you try like this

type on terminal update-alternatives --config java
and then select jdk 8 not else (select by number which jdk 8, if use linux or kali linux)
and enter

**Comment by kobocrew** [comment]
> @kobocrew
> 
> have you try like this
> 
> type on terminal update-alternatives --config java
> and then select jdk 8 not else (select by number which jdk 8, if use linux or kali linux)
> and enter

yes i did that, also i tried deleting java 11 and using only the java 8 version

**Comment by Lorenz11x** [comment]
Thanks for the kind reply, I tried but it doesn't work, I'll have to look
at it calmly, these are the versions

:~# update-alternatives --config java
There are 3 choices for the alternative java (providing /usr/bin/java).

  Selection    Path                                            Priority
Status
------------------------------------------------------------
  0            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111
 auto mode
  1            /usr/lib/jvm/java-10-openjdk-amd64/bin/java      1101
 manual mode
  2            /usr/lib/jvm/java-11-openjdk-amd64/bin/java      1111
 manual mode
* 3            /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java   1081
 manual mode

This is installed on a fixed notebook, , where I am also having problems
with Armitage, while the one installed in VM works great!
Thanks again and congratulations!

Il giorno mer 1 apr 2020 alle ore 17:33 kobocrew <notifications@github.com>
ha scritto:

**Comment by Enigma1024** [comment]
> How to install "openjdk-8-jre" on android. Thank you ^.^

Your JRE must be installed on your server, not on your client.

**Comment by Lorenz11x** [comment]
Thanks for the reply, but on kali linux 2020 VM works very well, on kali
linux installed on a fixed machine it gives this problem !! This
  "* 3 / usr / lib / jvm / java-8-openjdk-amd64 / jre / bin / java 108
manual mode" is also installed on kali linux VM equally.

Il giorno sab 18 apr 2020 alle ore 23:31 Enigma1024 <
notifications@github.com> ha scritto:

**Comment by bankofamerica-xx** [comment]
anyway i tried all of your suggestions and still have the same problem java not installed so what platform or system we should use to make it working like videos ???

**Comment by rex007m** [comment]
if you have installed Java 8
Then do edit out includes/apkBuilder.js
comment out  some lines.

```
spawn.stderr.on('data', (data) => {
       //data = data.toString().split('\n')[0];
       var javaVersion = "1.8"; //new RegExp('java version').test(data) ? data.split(' ')[2].replace(/"/g, '') : false;
       //  var openJDKVersion = new RegExp('openjdk version').test(data) ? data.split(' ')[2].replace(/"/g, '') : false;
       //  if (javaVersion || openJDKVersion) {
           spawn.removeAllListeners();
           spawn.stderr.removeAllListeners();
           return callback(null, javaVersion);
     //  } else return callback("Java Not Installed" + data , undefined);
   });
```

Just Disable Auto version And feed Manual Version.
This trick works on kali 2020

**Comment by Jack-Rogers** [comment]
Wow! This issue has grown big now! 
I've pushed an update V1.1.2 that should fix this issue, you'll know if this fix applies to you if when you run `java -version` you see something like this on the first line 
`Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true` 
instead of this
`openjdk version "1.8.0_212"`

Here's the link to download the latest version https://github.com/D3VL/L3MON/releases/tag/1.1.2

If this is confirmed to have fixed the issue, I'll close this thread

**Comment by rex007m** [comment]
log of output variable; so i think problem is solved. 

index > Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true             
index > openjdk version "1.8.0_212"
index > OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1-b01)
index > OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)

**Comment by Jack-Rogers** [comment]
@rex007m Thanks for confirming, and thank you everyone that provided logs/suggestions! 
I'll close this issue now - if anyone else is still having issues with this, please leave a comment below and I'll investigate, though as far as I'm concerned now, the root issue here has been fixed.

**Comment by yatharthmaheshwari** [comment]
sir You can You have a teamviewer session with me...

**Comment by kaushik09090** [comment]
sir i am having an issue 
==>Wrong Java Version Installed. Detected openjdk version "9.0.4" Ope. Please use Java 1.8.0 
and my java version is:-
root@kali:~# java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-3)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-3, mixed mode)
root@kali:~# 
WHAT SHOULD i DO.....

**Comment by kaushik09090** [comment]
sir i am having an issue 
==>Wrong Java Version Installed. Detected openjdk version "9.0.4" Ope. Please use Java 1.8.0 
and my java version is:-
root@kali:~# java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-3)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-3, mixed mode)
root@kali:~# 
WHAT SHOULD i DO.....

**Comment by kaushik09090** [comment]
sir i am having an issue 
==>Wrong Java Version Installed. Detected openjdk version "9.0.4" Ope. Please use Java 1.8.0 
and my java version is:-
root@kali:~# java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-3)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-3, mixed mode)
root@kali:~# 
WHAT SHOULD i DO.....

**Comment by kaushik09090** [comment]
sir i am having an issue 
==>Wrong Java Version Installed. Detected openjdk version "9.0.4" Ope. Please use Java 1.8.0 
and my java version is:-
root@kali:~# java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-3)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-3, mixed mode)
root@kali:~# 
WHAT SHOULD i DO.....

**Comment by kaushik09090** [comment]
sir i am having an issue 
==>Wrong Java Version Installed. Detected openjdk version "9.0.4" Ope. Please use Java 1.8.0 
and my java version is:-
root@kali:~# java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-3)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-3, mixed mode)
root@kali:~# 
WHAT SHOULD i DO.....

**Comment by kaushik09090** [comment]
sir i am having an issue 
==>Wrong Java Version Installed. Detected openjdk version "9.0.4" Ope. Please use Java 1.8.0 
and my java version is:-
root@kali:~# java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-3)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-3, mixed mode)
root@kali:~# 
WHAT SHOULD i DO.....

**Comment by kaushik09090** [comment]
sir i am having an issue 
==>Wrong Java Version Installed. Detected openjdk version "9.0.4" Ope. Please use Java 1.8.0 
and my java version is:-
root@kali:~# java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-3)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-3, mixed mode)
root@kali:~# 
WHAT SHOULD i DO.....

**Comment by kaushik09090** [comment]
sir i am having an issue 
==>Wrong Java Version Installed. Detected openjdk version "9.0.4" Ope. Please use Java 1.8.0 
and my java version is:-
root@kali:~# java -version
openjdk version "9.0.4"
OpenJDK Runtime Environment (build 9.0.4+12-Debian-3)
OpenJDK 64-Bit Server VM (build 9.0.4+12-Debian-3, mixed mode)
root@kali:~# 
WHAT SHOULD i DO.....
