### ISSUE TITLE
on some devices upon restart the apk crashed

### ISSUE THREAD

**Issue by bakree786** [D3VL/L3MON#22]
on some devices upon start the process manager stopped unexpectedly error

**Comment by Jack-Rogers** [comment]
Could you please provide more information.

**Comment by bakree786** [comment]
its crashing on restart and some time when internet is not available mostly Samsung phone a10 j7 the os is android 9 on these phones

**Comment by Jack-Rogers** [comment]
By more information; 
Please provide a ADB LOG of the application crashing.
I'll look into the no internet issue, does your phone have some form of battery management that could be killing the app?

**Comment by bakree786** [comment]
yeah i will provide you the log well yes but i excluded app from battery optimization

**Comment by Jack-Rogers** [comment]
-- Closing as no further information supplied
