### ISSUE TITLE
Web Interface

### ISSUE THREAD

**Issue by Shirokai988** [D3VL/L3MON#25]
Hello i already install and when i put pm2 start index.js all working i put my ip with port 22533 and no connect how allow ports or how to fix ?

**Comment by Jack-Rogers** [comment]
Have you got the port open in the firewall?

**Comment by Shirokai988** [comment]
I no how check I use kali linux

**Comment by Shirokai988** [comment]
> Have you got the port open in the firewall?

Are you help me ?

**Comment by Jack-Rogers** [comment]
Sorry, We can't provide specific OS support for everyone, please have a look on google for how to open ports. Additionally, how are you trying to access the web panel? have you got the right IP, are you using localhost? please provide more information.

**Comment by Jack-Rogers** [comment]
Closing as non-issue
