### ISSUE TITLE
Keeps disconnecting

### ISSUE THREAD

**Issue by ptahchiev** [D3VL/L3MON#29]
Socker.io keeps disconnecting and reconnecting again. I even changed the ping period to 15000 but still the same behaviour :(

**Comment by Jack-Rogers** [comment]
Is it possible the phone has battery management software that's killing the process? 
How long does the session stay open for before reconnecting?

**Comment by ptahchiev** [comment]
Hi @Jack-Rogers ,
what kind of battery-management software is this? How can I check it? I think the session disconnects  about 5-6 seconds after I lock my phone.. then it reconnects again after several minutes. And so every couple of minutes it disconnects and reconnects again.

**Comment by Jack-Rogers** [comment]
It depends on what device you're running this on. It's normal for the WebSocket connection to be killed when the phone is off, as soon as the phone is unlocked again the app will start polling the server for a new connection. this is why we built-in command queuing so you can request data from a device while its not connected and then have it sent back to the server as soon as it reconnects.

**Comment by ptahchiev** [comment]
Hmm.. i'm not sure this is 100% true.. Once I lock my screen, the connection is closed, but then after a few minutes I keep refreshing the admin panel and I can see it comes back online for about 20-30 seconds. After that it is lost again .. and this cycle keeps repeating.
What I would like to do it is keep the socket open even if the phone is locked.

**Comment by Jack-Rogers** [comment]
Again, this is most likely down to a battery management software running, try taking a log of the phone while its off to see if anything triggers it to close down. 
Why do you need the device to maintain a constant connection?

**Comment by Jack-Rogers** [comment]
-- closing as non-issue
