### ISSUE TITLE
Log SMS

### ISSUE THREAD

**Issue by Skladak04** [D3VL/L3MON#31]
Hello, sorry for my bad english, but I have a small problem namely that the SMS Log should display the latest log at the top of the page, and the older the lower

**Comment by Jack-Rogers** [comment]
That should be what the panel is displaying at the moment. 


If this is not the case you can change this line https://github.com/D3VL/L3MON/blob/20897ae4d2deabc108eaf487857e7441cc809f1b/server/includes/clientManager.js#L387 to 
```JavaScript
pageData = clientData.SMSData.reverse();
```
