### ISSUE TITLE
How can I host on aws or digital ocean?

### ISSUE THREAD

**Issue by i-am-nuralam** [D3VL/L3MON#32]
Hello developer, can I host this on aws or digital ocean? If yes then please tell me how?

**Comment by Jack-Rogers** [comment]
Yes. That's what it's designed for. please follow the installation guide. 
https://github.com/D3VL/L3MON#installation

**Comment by SHREYANK007** [comment]
@Jack-Rogers can you tell me how to host l3mon in aws
