### ISSUE TITLE
app only listen in ipv6

### ISSUE THREAD

**Issue by edayasaki** [D3VL/L3MON#34]
after running the app, the app works fine. but the app only listen in ipv6.

**Comment by Jack-Rogers** [comment]
Please try changing
https://github.com/D3VL/L3MON/blob/20897ae4d2deabc108eaf487857e7441cc809f1b/server/index.js#L68 To 
```JavaScript
app.listen(CONST.web_port, '0.0.0.0'); 
```

**Comment by Jack-Rogers** [comment]
-- closing as assumed fixed

**Comment by edayasaki** [comment]
-- reopened

yes app is now listening on ipv4, but the socket doesnt.

here's the netstat:
root@sgx:/var/www/appjs/add# netstat -pln
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:80              0.0.0.0:*               LISTEN      14283/nginx: master
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      6534/sshd
tcp        0      0 0.0.0.0:65432           0.0.0.0:*               LISTEN      4475/postgres
tcp        0      0 0.0.0.0:65530           0.0.0.0:*               LISTEN      2364/node /var/www/ --> web ui.
tcp        0      0 0.0.0.0:443             0.0.0.0:*               LISTEN      14283/nginx: master
tcp6       0      0 :::22                   :::*                    LISTEN      6534/sshd
tcp6       0      0 :::65432                :::*                    LISTEN      4475/postgres
tcp6       0      0 :::65531                :::*                    LISTEN      2364/node /var/www/ --> control port to connect to android
udp        0      0 0.0.0.0:68              0.0.0.0:*                           399/dhclient
udp        0      0 0.0.0.0:68              0.0.0.0:*                           363/dhclient
