### ISSUE TITLE
Dashboard

### ISSUE THREAD

**Issue by Skladak04** [D3VL/L3MON#38]
I wanted to ask if it is possible to implement Argon Dashboard Nodejs in this project

**Comment by Jack-Rogers** [comment]
Sure you can, what's up with the current frontend though?

**Comment by Skladak04** [comment]
And overall I edit the whole project a bit, but I have some problems with semantic ui and that's why I was thinking about moving the project to argon dashboard

**Comment by Jack-Rogers** [comment]
Sure, Go for it! it'll be interesting to see, maybe implement a feature to switch the UI between the two and make a pull request!
