### ISSUE TITLE
Does not run on Android version 10

### ISSUE THREAD

**Issue by mantapboskuh** [D3VL/L3MON#39]
Does not run on Android 10

**Comment by Jack-Rogers** [comment]
I've been developing this with android 10. it definitely runs!

Could you get a LOG of the app installing and "not running" please?

**Comment by kumarmintu** [comment]
> I've been developing this with android 10. it definitely runs!
> 
> Could you get a LOG of the app installing and "not running" please?

Sir it's not running in Android 10. As soon as we download the apk file and run it on the device and error of "App not installed" is thrown.😥
