### ISSUE TITLE
InfoSection and Mic Issues

### ISSUE THREAD

**Issue by sleepingspy999** [D3VL/L3MON#42]
Info section always has same date and time for first seen and last seen.
Also mic recording doesn't seem to work tried on android 6 and android 10 devices just creates a blank file,
Will this only work during a call or it it supposed to work at any time ?
Thanks tho really good project.

**Comment by Jack-Rogers** [comment]
Could you please provide logs of the phone when running the Mic capture command? Thank!

**Comment by Jack-Rogers** [comment]
Closing this as no further information has been provided.
