### ISSUE TITLE
Java error

### ISSUE THREAD

**Issue by Try2swipe** [D3VL/L3MON#43]
EVerytime I try to build a new apk this is shown to me:

Sign Command Failed - Command failed: java -jar "/tmp/L3MON/server/app/factory/sign.jar" "/tmp/L3MON/server/assets/webpublic/build.apk" Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more 

Any idea of what to do? Thanks :(

**Comment by Jack-Rogers** [comment]
Please make sure you're using java 1.8.*
You can check this by running `java -version`

**Comment by Try2swipe** [comment]
> Please make sure you're using java 1.8.*
> You can check this by running `java -version`

Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true
openjdk version "11.0.6" 2020-01-14
OpenJDK Runtime Environment (build 11.0.6+10-post-Debian-1)
OpenJDK 64-Bit Server VM (build 11.0.6+10-post-Debian-1, mixed mode, sharing)
