### ISSUE TITLE
Builder isn't working

### ISSUE THREAD

**Issue by Try2swipe** [D3VL/L3MON#44]
Every time I try to build an APK this is shown to me:

10/02/2020, 09:19:20 => ERROR | Build Failder - File Patch Error - READ

Direct from the event log, help please, I have no clue about what's happening, I got the latest java version installed already btw

**Comment by devilzz1337** [comment]
Please uninstall your latest java 
Then install java 1.8.0

**Comment by Try2swipe** [comment]
> Please uninstall your latest java
> Then install java 1.8.0

Solved, thanks
