### ISSUE TITLE
Add users option 

### ISSUE THREAD

**Issue by devilzz1337** [D3VL/L3MON#47]
Please add users option for use this server in the login page .

Like This 

![36df7a78c5dfd0531dd51caad74a01b5](https://user-images.githubusercontent.com/51515801/74229298-50cfa600-4cec-11ea-80d3-f595bd97fde7.jpg)

**Comment by Jack-Rogers** [comment]
Thanks for the suggestion.
How would you envision clients be allocated to users? would you have 1 super user that can allocate a client to a specific user, or would all users have access to all clients? please add some more context.

**Comment by Jack-Rogers** [comment]
-- closing as non-issue, more info still needed
