### ISSUE TITLE
Keylogger

### ISSUE THREAD

**Issue by develogo** [D3VL/L3MON#48]
It could have a feature to capture the keys, like a keylogger. And it would also capture the title of the window in question.
Example:
`Date 2020-02-12 | com.whatsapp | WhatsApp - Jack Jolie | Keys: I tried, I'm sorry [Submited]`

I imagine that for that, you have to have accessibility permission.  I've seen this feature in a similar application, called Spy Max 2.0 ('https://www.sa3ka.com/cc/threads/721/')

**Comment by Jack-Rogers** [comment]
We will look into implementing this, Thank you!
