### ISSUE TITLE
Not showing devices

### ISSUE THREAD

**Issue by vrushabhdhoke** [D3VL/L3MON#50]
Everything works fine.Apk builded, downloaded, installed.gave all permissions, but in device section it not showing up the phone.not offline nor online.

**Comment by Jack-Rogers** [comment]
Have you correctly set the URL of the server L3MON is running on?

**Comment by vrushabhdhoke** [comment]
Yes,its mine Ip address only.

**Comment by Jack-Rogers** [comment]
Just gonna close this as it's a contained issue.
Is the device and server on the same network, or is it on a remote server? If so have you opened ports 22533 and 22222?
