### ISSUE TITLE
unable to open L3MON

### ISSUE THREAD

**Issue by rishantkaushik988** [D3VL/L3MON#52]
**This is an issue with the**
- [x] Server
- [ ] Client
- [ ] Other

**Describe the bug**
After the installation of L3MON on kali machine and when we went to change the username& password of L3MON i am unble to modify and also unable to open the L3MON login page on firefox to do any work.

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Server Issue (please complete the following information):**
 - OS: [e.g. Linux, Windows]
 - OS Version: [e.g. Ubuntu, Windows 10]
 - Browser: [e.g. chrome, safari]

**Client Issue:**
 - Android Version: [e.g. Android 8]

**Checklist**
 - [ ] Is this really an issue?
 - [ ] Have I looked at previous issues to see if this has already been addressed?
 - [ ] Have I used some initiative to try and solve the issue myself?

**Comment by Jack-Rogers** [comment]
Did you follow the guide step by step?
Make sure to STOP L3MON before editing the username and password.
Are you using port 22533 to access the webserver? <IP HERE>:22533

**Comment by rishantkaushik988** [comment]
Sir I have follow the guide step by step to download L3MON  but sir  I am
still unable to get access and as your given web server is 22533 I used it
many times   but web server showing  error "unable to connect"

**Comment by Jack-Rogers** [comment]
Closing this as it's a contained issue. 
This is most likely down to a misconfiguration on your machine, please check that you can access the ports on the remote machine.
