### ISSUE TITLE
maindb.json is missing

### ISSUE THREAD

**Issue by aizaz12** [D3VL/L3MON#53]
![l3mon](https://user-images.githubusercontent.com/40170648/74626925-185c1c00-5173-11ea-8f38-fb957b61a285.PNG)
i downloaded the l3mon.zip but i couldnot find the maindb.json file. kindly fix the issue

**Comment by Jack-Rogers** [comment]
Please read the guide, you must first install the dependencies and then run L3MON to generate this file.

**Comment by darkwhitehat** [comment]
I have de same issue.
When I launch index.js with pm2, the maindb.json is not created. Why ?
I am on debian

**Comment by yatharthmaheshwari** [comment]
hey Bro, if you just want it to work so can install Ubuntu on virtual machine because it's a lot easier their

**Comment by Jack-Rogers** [comment]
> I have de same issue.
> When I launch index.js with pm2, the maindb.json is not created. Why ?
> I am on debian

again, please read the documentation; it states that you must first run `pm2 stop index`
If this doesn't solve the issue, it's likely down to file permissions. check node can write to the local filesystem.
