### ISSUE TITLE
Doesn't work on Samsung Devices

### ISSUE THREAD

**Issue by thezawad** [D3VL/L3MON#54]
**This is an issue with the**
- [] Server
- [x] Client
- [ ] Other

**Describe the bug**
I have tried multiple times with my Samsung device to make it usable. Looks like does not work on samsung devices for now, even after explicitly giving permission

**Comment by thezawad** [comment]
Morever, client suddenly gets disconnected.

**Comment by Jack-Rogers** [comment]
Please check that there's no battery management software killing the background tasks.
If this doesn't help please provide an ADB log of the application closing, this will help us narrow down the issue.

**Comment by thezawad** [comment]
Looks like it was an issue on my side.  But the App icon doesn't hide in app drawer.

Now working fine on Samsung device with real ip.

Is it possible to hide it in app drawer of samsung ui?

**Comment by Jack-Rogers** [comment]
Interesting, the icon should hide on first run. 
I'm going to close this issue for now as the original issue is fixed.
however, could you please provide android version, device version and build id's so I can look into why the icon isn't hiding? Cheers.

**Comment by thezawad** [comment]
It is android version 10
And one ui version 2.0
I am not sure about how to check build id

**Comment by Jack-Rogers** [comment]
And what phone is it, please?

**Comment by thezawad** [comment]
Galaxy A51

**Comment by maherobaid15** [comment]
Just adding here that the icon also still remains on my Huwaei device VOG-L04 Build number 10.0.0.178 EMUI version 10.0.0 and android version 10

**Comment by Jack-Rogers** [comment]
Thanks both, I'll look into this. Does it still persist after a reboot? 
I suspect this is down to custom launchers ignoring the fact that the icon should be hidden.

**Comment by maherobaid15** [comment]
Aha, it probably is the case, not sure what the default launcher for EMUI is but I suspect it's their own that comes bundled with their Android fork.
