### ISSUE TITLE
Can not login

### ISSUE THREAD

**Issue by H4A-HUB** [D3VL/L3MON#56]
**This is an issue with the**
- [] Server
- [] Client
- [X] Other

**Describe the bug**

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Server Issue (please complete the following information):**
 - OS: [e.g. Linux, Windows]
 - OS Version: [e.g. Ubuntu, Windows 10]
 - Browser: [e.g. chrome, safari]

**Client Issue:**
 - Android Version: [e.g. Android 8]

**Checklist**
 - [ ] Is this really an issue?
 - [ ] Have I looked at previous issues to see if this has already been addressed?
 - [ ] Have I used some initiative to try and solve the issue myself?

**Comment by develogo** [comment]
Did you edit main db.json? Remembering that the password has to be an MD5 hash

**Comment by H4A-HUB** [comment]
I changed the password and restarted the server, but I still can't log in

Vào 17:38, Th 6, 21 thg 2, 2020 Felipe Andrade <notifications@github.com>
đã viết:

**Comment by Jack-Rogers** [comment]
Firstly, please use the template provided. You gave no information of your issue in detail.

Secondly, is the md5 hash correct and in lowercase? How did you generate it?

**Comment by H4A-HUB** [comment]
I generate MD5 code with an online MD5 code generator, can it be used ?

**Comment by Jack-Rogers** [comment]
yes, it can, however the MD5 NEEDS to be lowercase! please ensure this is the case, and also check that you made the correct MD5 for the password you're attempting to use and haven't made a simple spelling mistake!

I'm going to close this issue as it's contained, however, will monitor for replys.

**Comment by KoustavDey** [comment]
l3mon is not taken login after I'm put id and password
