### ISSUE TITLE
Clipboard Log isn't working

### ISSUE THREAD

**Issue by vasuratanpara** [D3VL/L3MON#58]
**This is an issue with the**
- [x] Server
- [ ] Client
- [ ] Other

**Describe the bug**
Clipboard Log isn't working. It doesn't even have "UPDATE" button

**Screenshots**
![image](https://user-images.githubusercontent.com/15255654/75100960-75a50280-55a3-11ea-8f64-6152f34268c1.png)

**Server Issue (please complete the following information):**
 - OS: [Linux]
 - OS Version: [Ubuntu]
 - Browser: [chrome]

**Client Issue:**
 - Android Version : 10

**Checklist**
 - [x] Is this really an issue?
 - [x] Have I looked at previous issues to see if this has already been addressed?
 - [ ] Have I used some initiative to try and solve the issue myself?

**Comment by Jack-Rogers** [comment]
Clipboard log updates automatically when something is copied on the device. Please ensure you have allowed the right permissions.
