### ISSUE TITLE
Wrong time displaying in FIRST SEEN and LAST SEEN in "Info"

### ISSUE THREAD

**Issue by vasuratanpara** [D3VL/L3MON#60]
**This is an issue with the**
- [x] Server
- [ ] Client
- [ ] Other

**Describe the bug**
Wrong time displaying in FIRST SEEN and LAST SEEN in "Info". It isn't displaying correct up to date time. It is showing a static time I guess.

**Expected behavior**
FIRST SEEN and LAST SEEN time should be display correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/15255654/75101217-f1ed1500-55a6-11ea-8d5e-8217d4a5ec3d.png)

**Server Issue (please complete the following information):**
 - OS: [Linux]
 - OS Version: [Ubuntu 18.04 LTS]
 - Browser: [chrome]

**Client Issue:**
 - Android Version: 10

**Checklist**
 - [x] Is this really an issue?
 - [x] Have I looked at previous issues to see if this has already been addressed?
 - [ ] Have I used some initiative to try and solve the issue myself?

**Comment by Jack-Rogers** [comment]
Check the time on the L3MON host is correct. 
IIRC Last Seen updates every time the device establishes a connection to L3MON.
