### ISSUE TITLE
There should be an option (a button) to delete downloaded files from server 

### ISSUE THREAD

**Issue by vasuratanpara** [D3VL/L3MON#61]
**Is your feature request related to a problem? Please describe.**
If someone wants to delete files from server then they cannot delete directly.

**Describe the solution you'd like**
There should be a button to delete downloaded files from server 

**Describe alternatives you've considered**
There should be a button besides "SAVE", "OPEN" and "DELETE" in given screenshot

**Additional context**
![image](https://user-images.githubusercontent.com/15255654/75101309-9ae83f80-55a8-11ea-9de3-3ca7f963a017.png)

**Comment by Jack-Rogers** [comment]
Will look at adding this in a future release
