### ISSUE TITLE
APK Builder: ERROR | Build failed.

### ISSUE THREAD

**Issue by donihalim** [D3VL/L3MON#64]
Hi. First i'd like to thank you for this awesome project.

I got an error when trying to build an apk, it's stuck on finalizing after popup error message.
Here's the error log : 
```
23/02/2020, 00:36:36 => ERROR | Build Failed - Build Command Failed - Command failed: java -jar "/home/pi/lemon/app/factory/apktool.jar" b "/home/pi/lemon/app/factory/decompiled" -o "/home/pi/lemon/assets/webpublic/build.apk" S: WARNING: Could not write to (/root/.local/share/apktool/framework), using /tmp instead... S: Please be aware this is a volatile directory and frameworks could go missing, please utilize --frame-path if the default storage directory is unavailable W: /tmp/brut_util_Jar_5388510457602329818.tmp: 17: /tmp/brut_util_Jar_5388510457602329818.tmp: Syntax error: "(" unexpected brut.androlib.AndrolibException: brut.common.BrutException: could not exec (exit code = 2): [/tmp/brut_util_Jar_5388510457602329818.tmp, p, --forced-package-id, 127, --min-sdk-version, 11, --target-sdk-version, 24, --version-code, 1, --version-name, 1.0, --no-version-vectors, -F, /tmp/APKTOOL7447892577591737458.tmp, -0, arsc, -0, png, -0, arsc, -I, /tmp/1.apk, -S, /home/pi/lemon/app/factory/decompiled/res, -M, /home/pi/lemon/app/factory/decompiled/AndroidManifest.xml]
```
My system : 
Device : Raspberry Pi 1B
Os: Raspbian Buster
```
$ java --version
openjdk version "1.8.0_212" OpenJDK Runtime Environment (build 1.8.0_212-8u212-b01-1+rpi1-b01)
OpenJDK Client VM (build 25.212-b01, mixed mode)
```
```
$ node --version
v10.15.2
```
```
$ npm version
5.8.0
```
Thank you very much 😊

**Comment by yatharthmaheshwari** [comment]
Go to the folder where you have installed it and from there go to

>assets>webpublic>**build.apk**

there will be an error shown and it will stuck at finalizing but the apk file will be created.

then install that build.apk file in victim's file and test

**Comment by donihalim** [comment]
I hope so, but unfortunately there's only `build.s.apk` :(

**Comment by yatharthmaheshwari** [comment]
For some peaple the finalizing is stuck But the apk file is created.
just the difference is that is not signed.

so i found the apk and signed with easy apk tool But still it did'nt work for me.
that means the apk is corrupt
![signing faile](https://user-images.githubusercontent.com/42062688/75106449-d6cfe300-5642-11ea-975a-a746c2655294.PNG)
![signed](https://user-images.githubusercontent.com/42062688/75106451-d899a680-5642-11ea-8ef9-89eee0dcbce7.PNG)

**Comment by peterwilliam860** [comment]
I seem to be also getting a similar issue building the apk. This is my error message:

`2/24/2020, 1:41:45 AM => ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/home/william/projects/security/L3MON-master/server/app/factory/sign.jar" "/home/william/projects/security/L3MON-master/server/assets/webpublic/build.apk" Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more `

**Comment by Jack-Rogers** [comment]
@peterwilliam860 that is because you're not using Java 1.8
<hr> 
@donihalim This is the first time I've seen this error! Could you please try running L3MON as root?

**Comment by yatharthmaheshwari** [comment]
Now i'm 

> @peterwilliam860 that is because you're not using Java 1.8
> 
> @donihalim This is the first time I've seen this error! Could you please try running L3MON as root?

jack, Now I'm using Java 1.8.0 ( or i am?)

check this out
![java 8](https://user-images.githubusercontent.com/42062688/75201827-916cfc00-578f-11ea-83ca-ccb4c246758b.PNG)

and Yo! the Java not installed error still persist's

i'm down to a "anydesk" Session that may help You Fix this Bug Faster

**Comment by donihalim** [comment]
> @peterwilliam860 that is because you're not using Java 1.8
> 
> @donihalim This is the first time I've seen this error! Could you please try running L3MON as root?

Yes, i also try running L3MON as root, but got the same error

**Comment by peterwilliam860** [comment]
> > @peterwilliam860 that is because you're not using Java 1.8
> > @donihalim This is the first time I've seen this error! Could you please try running L3MON as root?
> 
> Yes, i also try running L3MON as root, but got the same error

Changing my default java to 1.8 worked for me, thanks @donihalim

**Comment by yatharthmaheshwari** [comment]
Lucky for You!

**Comment by Jack-Rogers** [comment]
@yatharthmaheshwari I'd be interested to have a quick anyscreen session as I can't seem to replicate this issue. please drop me an email > jack@d3vl.com and we can arrange a time.

**Comment by Kellyfends007** [comment]
how to fix ?
