### ISSUE TITLE
java not install ?

### ISSUE THREAD

**Issue by wantedhg** [D3VL/L3MON#67]
ERROR | Build Failed - Sign Command Failed - Command failed: java -jar "/root/Masaüstü/L3MON/app/factory/sign.jar" "/root/Masaüstü/L3MON/assets/webpublic/build.apk" Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on -Dswing.aatext=true Exception in thread "main" java.lang.NoClassDefFoundError: sun/misc/BASE64Encoder at s.Sign.addDigestsToManifest(Sign.java:108) at s.Sign.sign(Sign.java:454) at s.Sign.main(Sign.java:532) Caused by: java.lang.ClassNotFoundException: sun.misc.BASE64Encoder at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581) at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178) at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521) ... 3 more

**Comment by Jack-Rogers** [comment]
Install Java 1.8. see #14 #19 #57 #28 or basically any other issue with java in the title 🙄
