### ISSUE TITLE
APK file is not generated

### ISSUE THREAD

**Issue by Tasker-123** [D3VL/L3MON#69]
This is an issue with the making of the payload of L3MON.
My system is Kali Linux 2019.4 Gnome.
In the screenshot there there is 0 bytes size of the build apk.
So the APK file is not created correctly.
Also Java error is shown when building the APK.

**Comment by Jack-Rogers** [comment]
> Also Java error is shown when building the APK.

please run `java -version` and send back the output

**Comment by Tasker-123** [comment]
![Uploading Screenshot from 2020-03-03 09-04-47.png…]()

**Comment by Tasker-123** [comment]
![Screenshot from 2020-03-03 09-04-47](https://user-images.githubusercontent.com/61541904/75740810-acf77a00-5d2e-11ea-9765-0af57416fd71.png)
This is the output of java -version.

**Comment by Jack-Rogers** [comment]
There's ya problem! as it's been noted countless times before in the issues, you NEED to be running java `1.8.0` NOT `11.0.*`
