### ISSUE TITLE
App Icon isn't hiding after installation (Android 10)

### ISSUE THREAD

**Issue by vasuratanpara** [D3VL/L3MON#72]
**This is an issue with the**
- [ ] Server
- [x] Client
- [ ] Other

**Describe the bug**
App Icon isn't hiding after installation (Android 10)

**Screenshots**
![Screenshot_20200228-182454~2](https://user-images.githubusercontent.com/15255654/75595144-379f5700-5a59-11ea-8bf0-4ad7ff7ca522.png)
![Screenshot_20200228-182505](https://user-images.githubusercontent.com/15255654/75595145-3837ed80-5a59-11ea-8e2e-6558f20fbae6.png)
![Screenshot_20200228-183012](https://user-images.githubusercontent.com/15255654/75595146-3837ed80-5a59-11ea-88fd-673ab2ab06c3.png)

**Client Issue:**
 - Android Version: 10

**Checklist**
 - [x] Is this really an issue?
 - [x] Have I looked at previous issues to see if this has already been addressed?
 - [ ] Have I used some initiative to try and solve the issue myself?

**Comment by Jack-Rogers** [comment]
You appear to have ticked 
- [x] Have I looked at previous issues to see if this has already been addressed?

Please see issue #54
