### ISSUE TITLE
Export Option Needed

### ISSUE THREAD

**Issue by kml13** [D3VL/L3MON#73]
Hi,
  I like your hard work on this...
It Was Awesome one.
Perfect Working... There is no Negative/no complexity on install and use.

i need some feature on this.
1. It will be better for all if there is an Export option (pdf / Excel) on Contact list and call logs.
2. Download folder or file option on File Explorer section.

Thanks

**Comment by Jack-Rogers** [comment]
We like both of those suggestions! Thanks, we will work to implement them for a future release!
