### ISSUE TITLE
Hii sir, I want to run two Lemon  application on, one single vps, is it possible..?

### ISSUE THREAD

**Issue by sandippshah** [D3VL/L3MON#89]
Hii sir, I want to run two Lemon  application on, one single vps, is it possible..?
If yes , 
So guide plz..!

**Comment by Jack-Rogers** [comment]
I've already answered this on your issue #9 please see issue #13 
Download L3MON into a different folder, change the mentioned ports and use pm2 start choosing a different name. the setup is otherwise the same.

**Comment by sandippshah** [comment]
Thanks 🥰

**Comment by yatharthmaheshwari** [comment]
@Jack-Rogers would you like to have an one on one session ...pleaseee
