### ISSUE TITLE
issue & want info

### ISSUE THREAD

**Issue by computergeek15** [D3VL/L3MON#90]
overall its a very nice job of developer .. i have found.. after some connection and disconnection frequently the app crashed and can't see online device .. and one more thing i want to ask.. where is the client data that we downloaded..?? i mean i grab the microphone clip and after that it shows what if i want to delete that clip.. where is the data? and one more thing i want to request.. what if i want to delete the client like from the web page .. i mean i run the app in local area network and the phone connects every time with different IP so how to delete it ?

**Comment by hackerimranahmed** [comment]
> overall its a very nice job of developer .. i have found.. after some connection and disconnection frequently the app crashed and can't see online device .. and one more thing i want to ask.. where is the client data that we downloaded..?? i mean i grab the microphone clip and after that it shows what if i want to delete that clip.. where is the data? and one more thing i want to request.. what if i want to delete the client like from the web page .. i mean i run the app in local area network and the phone connects every time with different IP so how to delete it ?

I think this fckn developer is uploading the data to his server and creating a ID. Now i need to start to reverse engineer this code.

**Comment by Jack-Rogers** [comment]
@hackerimranahmed, please do not spread false allegations like this, see my response to your issue #99 

@computergeek15  sorry I didn't get back to this sooner, if you also have a look at my reply to issue #99 you'll find how todo what you've asked there, cheers 👍
