### ISSUE TITLE
Bad login

### ISSUE THREAD

**Issue by Ammyy9908** [D3VL/L3MON#97]
**First i Start the server by pm2**
- [x] Server and edit maindb.json with vim
- [ ] Client
- [ ] Other

**Describe the bug**
Login failed bad login

**To Reproduce**
3. See error

**Expected behavior**

**Screenshots**

**Server Issue (please complete the following information):**
 - OS: [e.g. Linux, Windows]
 - OS Version: [e.g. Ubuntu, Windows 10]
 - Browser: [e.g. chrome, safari]

**Client Issue:**
 - Android Version: [e.g. Android 8]

**Checklist**
 - [ ] Is this really an issue?
 - [ ] Have I looked at previous issues to see if this has already been addressed?
 - [ ] Have I used some initiative to try and solve the issue myself?

**Comment by mex0r** [comment]
You need to compare your  password hash with stored pass hash ;)

**Comment by Jack-Rogers** [comment]
I'm closing this issue as it lacks all information. Please fill out the provided template including the checklist and reopen it.
