### ISSUE TITLE
WHERE ARE YOU SAVING THE APP DATA AND HOW TO DELETE THE CLIENT ??

### ISSUE THREAD

**Issue by hackerimranahmed** [D3VL/L3MON#99]
where is the client data that we downloaded..?? i mean i grab the microphone clip and after that it shows what if i want to delete that clip.. where is the data? and one more thing i want to request.. what if i want to delete the client like from the web page .. i mean i run the app in local area network and the phone connects every time with different IP so how to delete it ?

I want you to answer this Mr.Jack

**Comment by hackerimranahmed** [comment]
Mr.Jack are you uploading data to your own server ?

**Comment by hackerimranahmed** [comment]
I have completely deleted everything in client data folder, but still everything is showing up in web interface, are you storing the data on your server ??

**Comment by hackerimranahmed** [comment]
and whats the use of this https://www.googletagmanager.com/gtag/js?id=G-W6SP16VJD5 ?

**Comment by Jack-Rogers** [comment]
Hey, you'll find recordings, downloads, etc in `/assets/webpublic/client_downloads/`, and the client database files in `/clientData`

No user data is uploaded to any of D3VL's servers, we do not participate in collecting client data in any manner.

We use Google Analytics to measure performance and use of L3MON, it helps us get some really useful information about how and where our software is being used! 

In future, please refrain from spamming comments and contain your queries to one comment, Thanks!

**Comment by hackerimranahmed** [comment]
I have deleted everything from /assets/webpublic/client_downloads/ and the client database files in /clientData and i also did pm2 restart all, but when the client is visible as Offline, and when i click manage on Offline Client and click on Call Logs or Messages and click on update, then it says device offline and command is queued, but just in 30seconds again my old data is getting generated and im getting the list of it, and after that if i check in /clientData folder there comes a JSON file by Magic, how is this possible ???

**Comment by Jack-Rogers** [comment]
because it's cached in the nodejs process, first stop it, delete the files, and start it again.

**Comment by hackerimranahmed** [comment]
@Jack-Rogers 
http://192.168.31.190:22533/manage/erfdb8dde1eag8j47/info

can you pls guide me where can i find manage folder ?

**Comment by Jack-Rogers** [comment]
That is not a folder, it's a route in Express. 
Maybe take a moment to 
> Now I need to start to reverse engineer this code. #90

and learn how it works 😄

**Comment by hackerimranahmed** [comment]
@Jack-Rogers ill check once again thanks.. ill delete my comments when i feel that everything is okay, thanks for your response

**Comment by Jack-Rogers** [comment]
No problems, and no need to delete your comments 👍
It serves as a point of information should anybody else have concern.
